#############################################################################
# Makefile for building: MySqlTool.app/Contents/MacOS/MySqlTool
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  MySqlTool.pro
# Template: app
# Command: /Users/whisperchi/Qt5.7.1/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile MySqlTool.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers -I../../Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers -I../../Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -F/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib
QMAKE         = /Users/whisperchi/Qt5.7.1/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MySqlTool1.0.0
DISTDIR = /Users/whisperchi/work/MySqlTool/.tmp/MySqlTool1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SqlData.cpp \
		sqlite3.c qrc_qml.cpp \
		moc_SqlData.cpp
OBJECTS       = main.o \
		SqlData.o \
		sqlite3.o \
		qrc_qml.o \
		moc_SqlData.o
DIST          = ../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		MySqlTool.pro SqlData.h \
		sqlite3.h main.cpp \
		SqlData.cpp \
		sqlite3.c
QMAKE_TARGET  = MySqlTool
DESTDIR       = 
TARGET        = MySqlTool.app/Contents/MacOS/MySqlTool


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d MySqlTool.app/Contents/MacOS/ || mkdir -p MySqlTool.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MySqlTool.pro ../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		MySqlTool.pro \
		qml.qrc \
		../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/QtQml.prl \
		../../Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile MySqlTool.pro
../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf:
../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf:
MySqlTool.pro:
qml.qrc:
../../Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/QtQml.prl:
../../Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile MySqlTool.pro

qmake_all: FORCE

MySqlTool.app/Contents/PkgInfo: 
	@test -d MySqlTool.app/Contents || mkdir -p MySqlTool.app/Contents
	@$(DEL_FILE) MySqlTool.app/Contents/PkgInfo
	@echo "APPL????" > MySqlTool.app/Contents/PkgInfo
MySqlTool.app/Contents/Resources/empty.lproj: 
	@test -d MySqlTool.app/Contents/Resources || mkdir -p MySqlTool.app/Contents/Resources
	@touch MySqlTool.app/Contents/Resources/empty.lproj
	
MySqlTool.app/Contents/Info.plist: 
	@test -d MySqlTool.app/Contents || mkdir -p MySqlTool.app/Contents
	@$(DEL_FILE) MySqlTool.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.MySqlTool,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,MySqlTool,g" -e "s,@LIBRARY@,MySqlTool,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >MySqlTool.app/Contents/Info.plist

all: Makefile \
		MySqlTool.app/Contents/PkgInfo \
		MySqlTool.app/Contents/Resources/empty.lproj \
		MySqlTool.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents SqlData.h sqlite3.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp SqlData.cpp sqlite3.c $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r MySqlTool.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../Qt5.7.1/5.7/clang_64/bin/rcc \
		arrowLeft.png \
		MyRadioButton.qml \
		main.qml
	/Users/whisperchi/Qt5.7.1/5.7/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_SqlData.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SqlData.cpp
moc_SqlData.cpp: ../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		SqlData.h \
		../../Qt5.7.1/5.7/clang_64/bin/moc
	/Users/whisperchi/Qt5.7.1/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -I/Users/whisperchi/work/MySqlTool -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/whisperchi/Qt5.7.1/5.7/clang_64/lib SqlData.h -o moc_SqlData.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		../../Qt5.7.1/5.7/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		SqlData.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

SqlData.o: SqlData.cpp SqlData.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SqlData.o SqlData.cpp

sqlite3.o: sqlite3.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o sqlite3.o sqlite3.c

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_SqlData.o: moc_SqlData.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SqlData.o moc_SqlData.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/MySqlTool/bin || mkdir -p $(INSTALL_ROOT)/opt/MySqlTool/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/MySqlTool/bin/MySqlTool.app
	
	-$(INSTALL_DIR) MySqlTool.app $(INSTALL_ROOT)/opt/MySqlTool/bin/MySqlTool.app
	-$(STRIP) $(INSTALL_ROOT)/opt/MySqlTool/bin/MySqlTool.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/MySqlTool/bin/MySqlTool.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/MySqlTool/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

